# Generated by scripts/generate_design_assets.py
TOKENS = {
  "color": {
    "border": "#ffffff28",
    "critical": "#e85c54",
    "ok": "#5ec584",
    "surface": "#16161a",
    "text": "#ebebf0",
    "textDim": "#9696a0",
    "track": "#ffffff22",
    "warning": "#e8b04a"
  },
  "size": {
    "barHeight": 6,
    "compactWidth": 260,
    "expandedWidth": 300,
    "padding": 12,
    "radius": 14
  }
}
