from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).parents[1]
SOURCE = ROOT / "design" / "tokens.json"
PYTHON_OUTPUT = ROOT / "src" / "quotabubble" / "presentation" / "generated_tokens.py"
GJS_OUTPUT = ROOT / "gnome-shell-extension" / "generated" / "tokens.js"


def _render(node: dict[str, object], *, alpha_first: bool) -> dict[str, object]:
    values: dict[str, object] = {}
    for name, child in node.items():
        if not isinstance(child, dict):
            continue
        if "$value" in child:
            values[name] = _render_value(child, alpha_first=alpha_first)
        else:
            values[name] = _render(child, alpha_first=alpha_first)
    return values


def _render_value(token: dict[str, object], *, alpha_first: bool) -> object:
    value = token["$value"]
    alpha = token.get("$alpha")
    if token.get("$type") != "color" or alpha is None:
        return value
    rgb, alpha_hex = value.removeprefix("#"), f"{alpha:02x}"
    return f"#{alpha_hex}{rgb}" if alpha_first else f"#{rgb}{alpha_hex}"


def main() -> None:
    source = json.loads(SOURCE.read_text(encoding="utf-8"))
    # Qt's QColor(str) parses 8-digit hex as #AARRGGBB; CSS/GJS uses #RRGGBBAA.
    # Each target renders its own hex ordering from the same $value/$alpha components.
    qt_payload = json.dumps(_render(source, alpha_first=True), indent=2, sort_keys=True)
    web_payload = json.dumps(_render(source, alpha_first=False), indent=2, sort_keys=True)
    python_source = f"# Generated by scripts/generate_design_assets.py\nTOKENS = {qt_payload}\n"
    PYTHON_OUTPUT.write_text(python_source, encoding="utf-8")
    GJS_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    GJS_OUTPUT.write_text(
        f"// Generated by scripts/generate_design_assets.py\n"
        f"export const TOKENS = {web_payload};\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
