from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).parents[1]
SOURCE = ROOT / "design" / "tokens.json"
PYTHON_OUTPUT = ROOT / "src" / "quotabubble" / "presentation" / "generated_tokens.py"
GJS_OUTPUT = ROOT / "gnome-shell-extension" / "generated" / "tokens.js"


def _values(node: dict[str, object]) -> dict[str, object]:
    values: dict[str, object] = {}
    for name, child in node.items():
        if not isinstance(child, dict):
            continue
        if "$value" in child:
            values[name] = child["$value"]
        else:
            values[name] = _values(child)
    return values


def main() -> None:
    tokens = _values(json.loads(SOURCE.read_text(encoding="utf-8")))
    payload = json.dumps(tokens, indent=2, sort_keys=True)
    python_source = f"# Generated by scripts/generate_design_assets.py\nTOKENS = {payload}\n"
    PYTHON_OUTPUT.write_text(python_source, encoding="utf-8")
    GJS_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    GJS_OUTPUT.write_text(
        f"// Generated by scripts/generate_design_assets.py\nexport const TOKENS = {payload};\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
