from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).parents[1]
SOURCE = ROOT / "design" / "tokens.json"
PYTHON_OUTPUT = ROOT / "src" / "quotabubble" / "presentation" / "generated_tokens.py"
GJS_OUTPUT = ROOT / "gnome-shell-extension" / "generated" / "tokens.js"

# Design tokens use the CSS/DTCG #RRGGBBAA convention (alpha last), which GJS/CSS
# consumes natively. Qt's QColor(str) parses 8-digit hex as #AARRGGBB (alpha first),
# so Python-side tokens need their alpha byte moved to the front.
_ALPHA_HEX = re.compile(r"^#([0-9a-fA-F]{6})([0-9a-fA-F]{2})$")


def _values(node: dict[str, object]) -> dict[str, object]:
    values: dict[str, object] = {}
    for name, child in node.items():
        if not isinstance(child, dict):
            continue
        if "$value" in child:
            values[name] = child["$value"]
        else:
            values[name] = _values(child)
    return values


def _to_qt_alpha_order(value: object) -> object:
    if isinstance(value, str):
        match = _ALPHA_HEX.match(value)
        if match:
            rgb, alpha = match.groups()
            return f"#{alpha}{rgb}"
        return value
    if isinstance(value, dict):
        return {key: _to_qt_alpha_order(child) for key, child in value.items()}
    return value


def main() -> None:
    tokens = _values(json.loads(SOURCE.read_text(encoding="utf-8")))
    web_payload = json.dumps(tokens, indent=2, sort_keys=True)
    qt_payload = json.dumps(_to_qt_alpha_order(tokens), indent=2, sort_keys=True)
    python_source = f"# Generated by scripts/generate_design_assets.py\nTOKENS = {qt_payload}\n"
    PYTHON_OUTPUT.write_text(python_source, encoding="utf-8")
    GJS_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    GJS_OUTPUT.write_text(
        f"// Generated by scripts/generate_design_assets.py\n"
        f"export const TOKENS = {web_payload};\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
